source 'https://rubygems.org'

gem 'activeadmin', github: 'activeadmin'
gem 'bootstrap-sass'
gem 'cancancan', '~> 1.10'
gem 'delayed_job_active_record'
gem 'devise'
gem 'font-awesome-sass'
gem 'friendly_id'
gem 'haml-rails'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'pg'
gem 'paperclip'
gem 'rails', '4.2.0'
gem 'sass-rails'
gem 'simple_form'
gem 'therubyracer', platforms: :ruby
gem 'uglifier'

group :development do
  gem 'capistrano', '~> 3.1.0'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'populator'
  gem 'spring'
  gem 'web-console'
end

group :development, :test do
  gem 'awesome_print'
  gem 'bundler-audit', require: false
  gem 'byebug'
  gem 'capybara'
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'pry-rails'
  gem 'rails-dev-boost'
  gem 'rb-inotify', '>= 0.8.8'
  gem 'rspec-rails', '~> 3.0'
end

group :test do
  gem 'minitest-reporters', '1.0.5'
  gem 'mini_backtrace',     '0.1.3'
  gem 'guard-minitest',     '2.3.1'
  gem 'database_cleaner'
  gem 'formulaic'
  gem 'shoulda-matchers', require: false
  gem 'timecop'
  gem 'webmock'
end

group :staging, :production do
end
